server:
  port: 8001

spring:
  # 数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/shangcheng?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
  #reids
  redis:
    host: 127.0.0.1
    port: 6379

# mybatis-plus
mybatis-plus:
  mapper-locations: classpath*:cn/southwest/shop/mapper/xml/*.xml
logging:
  level:
    cn:
      meteor:
        beyondclouds: debug
    com:
      corundumstudio: info


dubbo:
  application:
    #应用名称
    name: applet-provider

  registry:
     #注册中心地址
    address: zookeeper://127.0.0.1:2181
      #超时时间
    timeout: 6000
  protocol:
    #协议名称
    name: dubbo
    #协议端口
    port: 20880
  scan:
    #服务所在的包
    base-packages: cn.southwest.shop.service.impl



